### ISSUE TITLE
Extract tags instead of milestones

### ISSUE THREAD

**Issue by jasonslyvia** [roshanca/autochangelog#3]
We don't actively use `milestones`, but we do tag every version when go to production. It is able to extract commit messages between tags instead of milestones?

**Comment by roshanca** [comment]
Great idea! 

Maybe next version. If you can offer some helpful forks are better:)

**Comment by roshanca** [comment]
There's an awesome one: https://github.com/tj/git-extras/blob/master/Commands.md#git-changelog
