### ISSUE TITLE
/usr/bin/env: node --harmony: No such file or directory  

### ISSUE THREAD

**Issue by andreroggeri** [roshanca/autochangelog#6]
I'm getting this error `/usr/bin/env: node --harmony: No such file or directory` when running the autochangelog command.

I'm on Ubuntu Gnome 15.04

**Comment by roshanca** [comment]
Have you got node > 4.0 installed? Which way you install?

**Comment by andreroggeri** [comment]
Yes

`andre@bumblebee:~$ /usr/bin/env node --version
v5.2.0`

As far as I remember, I installed via `apt-get`. But I'm not sure if I updated using other way after that.

**Comment by roshanca** [comment]
Sorry for replying not in time. Is this working for u: http://stackoverflow.com/questions/26320901/cannot-install-nodejs-usr-bin-env-node-no-such-file-or-directory

**Comment by andreroggeri** [comment]
Don't worry ! :)

I've already did that. npm runs normally on my setup.

Maybe related to [this](https://github.com/azproduction/node-mc/issues/3)

**Comment by roshanca** [comment]
Is there any more problem? @andreroggeri
